dbt_glue_demo:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: "{{ env_var('DBT_ATHENA_S3_LOCATION') }}"
      s3_data_dir: "{{ env_var('DBT_S3_LOCATION') }}"
      region_name: us-east-1
      database: awsdatacatalog
      schema: dbt_glue_demo_nyc_metrics
      work_group: athena-dbt-glue-aws-blog
      aws_profile_name: dbt